services:
  - type: web
    name: app-flask-acr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        value: 2d288172ecd5b61ac97539ebbb927bee06d9584fc7a3e813c727429811246e56
      - key: RENDER
        value: "true"

databases:
  - name: acr-db
    databaseName: ACR
    user: acr_user
    plan: free 