services:
  - type: web
    name: app-flask-acr
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        python3-dev \
        libpq-dev \
        unixodbc-dev \
        && pip install --upgrade pip \
        && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GITHUB_REPO_URL
        value: https://github.com/elcame/app-flask.git
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: RENDER
        value: true
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: acr-db
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_BUCKET_NAME
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: acr-db
    databaseName: ACR
    user: acr_user
    plan: free 