services:
  - type: web
    name: app-flask-acr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: acr-db
          property: connectionString
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 1

databases:
  - name: acr-db
    databaseName: ACR
    user: acr_user
    plan: free 