from .usuario_routes import usuario_bp
from .empresa_routes import empresa_bp
from .tractocamion_routes import tractocamion_bp
from .trabajadores_routes import trabajadores_bp
from .manifiesto_routes import manifiesto_bp
from .pagos_routes import pagos_bp
from .tanqueo_routes import tanqueo_bp
from .mantenimiento_routes import mantenimiento_bp
from .seguro_routes import seguro_bp